//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmManagementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Film
    {
        [Required]
        [RegularExpression(@"\d+", ErrorMessage = "Please Enter Only Numbers!")]
        public int FilmID { get; set; }
        [Required]
        [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "Please Enter Only Characters!")]
        public string Description { get; set; }
        [Required]
        [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "Please Enter Only Characters!")]
        public string Title { get; set; }
        [DataType(DataType.Date)]
        [Required]
        public DateTime ReleaseYear { get; set; }
        [DataType(DataType.Date)]
        [Required]
        public DateTime RentalDuration { get; set; }
        [Required]
        public decimal ReplacementCost { get; set; }
        [Required]
        [RegularExpression(@"\d+", ErrorMessage = "Please Enter Only Numbers!")]
        public int LanguageId { get; set; }
        [Required]
        [RegularExpression(@"\d+", ErrorMessage = "Please Enter Only Numbers!")]
        public decimal Length { get; set; }
        [Required]
        [RegularExpression(@"\d+", ErrorMessage = "Please Enter Only Numbers!")]
        public decimal Rating { get; set; }
        [Required]
        [RegularExpression(@"\d+", ErrorMessage = "Please Enter Only Numbers!")]
        public int ActorId { get; set; }
        [Required]
        [RegularExpression(@"\d+", ErrorMessage = "Please Enter Only Numbers!")]
        public int CategoryId { get; set; }
        public virtual Actor Actor { get; set; }
        public virtual Category Category { get; set; }
        public virtual Language Language { get; set; }
    }
}
